/*
@startuml
start

if ( actions ready? ) then (yes)
  :process all;
else (no)
  :process none;
endif

stop
@enduml
*/

start()

iff ('actions ready?' ) then ('yes')
  action('process all')
elsee ('no')
  action('process none')
endif()

stop()
