@startuml
start
switch (test?)
case ( conditionA )
  :Action 1;
case ( conditionB )
  :Action 2;
case ( conditionC )
  :Action 3;
case ( conditionD )
  :Action 4;
case ( conditionE )
  :Action 5;
endswitch
stop
@enduml
